# Build file for CD demo
#
# No real need for layer caching, this will be really quick to build

# Some useful repeated stanzas

docker-sign-in: &docker-sign-in
  name: Sign into Docker registry
  command: |
    docker login -u halfercode -p ${GITLAB_CDDEMO_REGISTRY_TOKEN} registry.gitlab.com

# Here are the jobs

version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      # We don't need remote Docker, but this gets the local Docker service started
      - setup_remote_docker
      - run: *docker-sign-in
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_PROJECT_REPONAME} .
            docker tag ${CIRCLE_PROJECT_REPONAME} registry.gitlab.com/halfercode/${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Push Docker image
          command: |
            docker push registry.gitlab.com/halfercode/${CIRCLE_PROJECT_REPONAME}

  # @todo This doesn't do any deploying yet, process needs designing and finishing
  deploy:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      # We don't need remote Docker, but this gets the local Docker service started
      - setup_remote_docker
      - run: *docker-sign-in

# @todo Check that tagged and untagged builds run 'build'
# @todo Check that deploy-tagged builds run 'deploy'

workflows:
  version: 2
  # This works on all pushes
  untagged-build:
    jobs:
      - build
  # This should only work on deploy tags
  tagged-build:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^deploy-.*/
