# Build file for CD demo
#
# No real need for layer caching, this will be really quick to build

version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Sign into Docker registry
          command: |
            docker login -u halfercode -p ${GITLAB_CDDEMO_REGISTRY_TOKEN} registry.gitlab.com
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_PROJECT_REPONAME} .
            docker tag ${CIRCLE_PROJECT_REPONAME} registry.gitlab.com/halfercode/${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Push Docker image
          command: |
            docker push registry.gitlab.com/halfercode/${CIRCLE_PROJECT_REPONAME}
